/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as MenuRouteImport } from './routes/menu'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated/account'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedBranchRouteImport } from './routes/_authenticated/branch'
import { Route as AuthenticatedFavoritesRouteImport } from './routes/_authenticated/favorites'
import { Route as AuthenticatedOrdersRouteImport } from './routes/_authenticated/orders'
import { Route as AuthenticatedVendorRouteImport } from './routes/_authenticated/vendor'
import { Route as FoodIdRouteImport } from './routes/food.$id'
import { Route as RIndexRouteImport } from './routes/r.index'
import { Route as RSlugRouteImport } from './routes/r.$slug'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminAnalyticsRouteImport } from './routes/_authenticated/admin.analytics'
import { Route as AuthenticatedAdminBranchesRouteImport } from './routes/_authenticated/admin.branches'
import { Route as AuthenticatedAdminCategoriesRouteImport } from './routes/_authenticated/admin.categories'
import { Route as AuthenticatedAdminCouponsRouteImport } from './routes/_authenticated/admin.coupons'
import { Route as AuthenticatedAdminFoodsRouteImport } from './routes/_authenticated/admin.foods'
import { Route as AuthenticatedAdminOrdersRouteImport } from './routes/_authenticated/admin.orders'
import { Route as AuthenticatedAdminReportsRouteImport } from './routes/_authenticated/admin.reports'
import { Route as AuthenticatedAdminRestaurantsRouteImport } from './routes/_authenticated/admin.restaurants'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin.users'
import { Route as AuthenticatedBranchIndexRouteImport } from './routes/_authenticated/branch.index'
import { Route as AuthenticatedBranchInventoryRouteImport } from './routes/_authenticated/branch.inventory'
import { Route as AuthenticatedBranchOrdersRouteImport } from './routes/_authenticated/branch.orders'
import { Route as AuthenticatedBranchReportsRouteImport } from './routes/_authenticated/branch.reports'
import { Route as AuthenticatedOrdersIdRouteImport } from './routes/_authenticated/orders.$id'
import { Route as AuthenticatedVendorIndexRouteImport } from './routes/_authenticated/vendor.index'
import { Route as AuthenticatedVendorAnalyticsRouteImport } from './routes/_authenticated/vendor.analytics'
import { Route as AuthenticatedVendorBranchesRouteImport } from './routes/_authenticated/vendor.branches'
import { Route as RSlugBranchCodeRouteImport } from './routes/r.$slug.$branchCode'
import { Route as AuthenticatedAdminRestaurantsIdRouteImport } from './routes/_authenticated/admin.restaurants.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuRoute = MenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBranchRoute = AuthenticatedBranchRouteImport.update({
  id: '/branch',
  path: '/branch',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFavoritesRoute = AuthenticatedFavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOrdersRoute = AuthenticatedOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedVendorRoute = AuthenticatedVendorRouteImport.update({
  id: '/vendor',
  path: '/vendor',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const FoodIdRoute = FoodIdRouteImport.update({
  id: '/food/$id',
  path: '/food/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RIndexRoute = RIndexRouteImport.update({
  id: '/r/',
  path: '/r/',
  getParentRoute: () => rootRouteImport,
} as any)
const RSlugRoute = RSlugRouteImport.update({
  id: '/r/$slug',
  path: '/r/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminAnalyticsRoute =
  AuthenticatedAdminAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminBranchesRoute =
  AuthenticatedAdminBranchesRouteImport.update({
    id: '/branches',
    path: '/branches',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCategoriesRoute =
  AuthenticatedAdminCategoriesRouteImport.update({
    id: '/categories',
    path: '/categories',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCouponsRoute =
  AuthenticatedAdminCouponsRouteImport.update({
    id: '/coupons',
    path: '/coupons',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminFoodsRoute = AuthenticatedAdminFoodsRouteImport.update({
  id: '/foods',
  path: '/foods',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminOrdersRoute =
  AuthenticatedAdminOrdersRouteImport.update({
    id: '/orders',
    path: '/orders',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminReportsRoute =
  AuthenticatedAdminReportsRouteImport.update({
    id: '/reports',
    path: '/reports',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminRestaurantsRoute =
  AuthenticatedAdminRestaurantsRouteImport.update({
    id: '/restaurants',
    path: '/restaurants',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedBranchIndexRoute =
  AuthenticatedBranchIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedBranchRoute,
  } as any)
const AuthenticatedBranchInventoryRoute =
  AuthenticatedBranchInventoryRouteImport.update({
    id: '/inventory',
    path: '/inventory',
    getParentRoute: () => AuthenticatedBranchRoute,
  } as any)
const AuthenticatedBranchOrdersRoute =
  AuthenticatedBranchOrdersRouteImport.update({
    id: '/orders',
    path: '/orders',
    getParentRoute: () => AuthenticatedBranchRoute,
  } as any)
const AuthenticatedBranchReportsRoute =
  AuthenticatedBranchReportsRouteImport.update({
    id: '/reports',
    path: '/reports',
    getParentRoute: () => AuthenticatedBranchRoute,
  } as any)
const AuthenticatedOrdersIdRoute = AuthenticatedOrdersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedOrdersRoute,
} as any)
const AuthenticatedVendorIndexRoute =
  AuthenticatedVendorIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedVendorRoute,
  } as any)
const AuthenticatedVendorAnalyticsRoute =
  AuthenticatedVendorAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedVendorRoute,
  } as any)
const AuthenticatedVendorBranchesRoute =
  AuthenticatedVendorBranchesRouteImport.update({
    id: '/branches',
    path: '/branches',
    getParentRoute: () => AuthenticatedVendorRoute,
  } as any)
const RSlugBranchCodeRoute = RSlugBranchCodeRouteImport.update({
  id: '/$branchCode',
  path: '/$branchCode',
  getParentRoute: () => RSlugRoute,
} as any)
const AuthenticatedAdminRestaurantsIdRoute =
  AuthenticatedAdminRestaurantsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAdminRestaurantsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/menu': typeof MenuRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/account': typeof AuthenticatedAccountRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/branch': typeof AuthenticatedBranchRouteWithChildren
  '/favorites': typeof AuthenticatedFavoritesRoute
  '/orders': typeof AuthenticatedOrdersRouteWithChildren
  '/vendor': typeof AuthenticatedVendorRouteWithChildren
  '/food/$id': typeof FoodIdRoute
  '/r/$slug': typeof RSlugRouteWithChildren
  '/r/': typeof RIndexRoute
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/branches': typeof AuthenticatedAdminBranchesRoute
  '/admin/categories': typeof AuthenticatedAdminCategoriesRoute
  '/admin/coupons': typeof AuthenticatedAdminCouponsRoute
  '/admin/foods': typeof AuthenticatedAdminFoodsRoute
  '/admin/orders': typeof AuthenticatedAdminOrdersRoute
  '/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/admin/restaurants': typeof AuthenticatedAdminRestaurantsRouteWithChildren
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/branch/inventory': typeof AuthenticatedBranchInventoryRoute
  '/branch/orders': typeof AuthenticatedBranchOrdersRoute
  '/branch/reports': typeof AuthenticatedBranchReportsRoute
  '/orders/$id': typeof AuthenticatedOrdersIdRoute
  '/vendor/analytics': typeof AuthenticatedVendorAnalyticsRoute
  '/vendor/branches': typeof AuthenticatedVendorBranchesRoute
  '/r/$slug/$branchCode': typeof RSlugBranchCodeRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/branch/': typeof AuthenticatedBranchIndexRoute
  '/vendor/': typeof AuthenticatedVendorIndexRoute
  '/admin/restaurants/$id': typeof AuthenticatedAdminRestaurantsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/menu': typeof MenuRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/account': typeof AuthenticatedAccountRoute
  '/favorites': typeof AuthenticatedFavoritesRoute
  '/orders': typeof AuthenticatedOrdersRouteWithChildren
  '/food/$id': typeof FoodIdRoute
  '/r/$slug': typeof RSlugRouteWithChildren
  '/r': typeof RIndexRoute
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/branches': typeof AuthenticatedAdminBranchesRoute
  '/admin/categories': typeof AuthenticatedAdminCategoriesRoute
  '/admin/coupons': typeof AuthenticatedAdminCouponsRoute
  '/admin/foods': typeof AuthenticatedAdminFoodsRoute
  '/admin/orders': typeof AuthenticatedAdminOrdersRoute
  '/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/admin/restaurants': typeof AuthenticatedAdminRestaurantsRouteWithChildren
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/branch/inventory': typeof AuthenticatedBranchInventoryRoute
  '/branch/orders': typeof AuthenticatedBranchOrdersRoute
  '/branch/reports': typeof AuthenticatedBranchReportsRoute
  '/orders/$id': typeof AuthenticatedOrdersIdRoute
  '/vendor/analytics': typeof AuthenticatedVendorAnalyticsRoute
  '/vendor/branches': typeof AuthenticatedVendorBranchesRoute
  '/r/$slug/$branchCode': typeof RSlugBranchCodeRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/branch': typeof AuthenticatedBranchIndexRoute
  '/vendor': typeof AuthenticatedVendorIndexRoute
  '/admin/restaurants/$id': typeof AuthenticatedAdminRestaurantsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/menu': typeof MenuRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/account': typeof AuthenticatedAccountRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/branch': typeof AuthenticatedBranchRouteWithChildren
  '/_authenticated/favorites': typeof AuthenticatedFavoritesRoute
  '/_authenticated/orders': typeof AuthenticatedOrdersRouteWithChildren
  '/_authenticated/vendor': typeof AuthenticatedVendorRouteWithChildren
  '/food/$id': typeof FoodIdRoute
  '/r/$slug': typeof RSlugRouteWithChildren
  '/r/': typeof RIndexRoute
  '/_authenticated/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/_authenticated/admin/branches': typeof AuthenticatedAdminBranchesRoute
  '/_authenticated/admin/categories': typeof AuthenticatedAdminCategoriesRoute
  '/_authenticated/admin/coupons': typeof AuthenticatedAdminCouponsRoute
  '/_authenticated/admin/foods': typeof AuthenticatedAdminFoodsRoute
  '/_authenticated/admin/orders': typeof AuthenticatedAdminOrdersRoute
  '/_authenticated/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/_authenticated/admin/restaurants': typeof AuthenticatedAdminRestaurantsRouteWithChildren
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/branch/inventory': typeof AuthenticatedBranchInventoryRoute
  '/_authenticated/branch/orders': typeof AuthenticatedBranchOrdersRoute
  '/_authenticated/branch/reports': typeof AuthenticatedBranchReportsRoute
  '/_authenticated/orders/$id': typeof AuthenticatedOrdersIdRoute
  '/_authenticated/vendor/analytics': typeof AuthenticatedVendorAnalyticsRoute
  '/_authenticated/vendor/branches': typeof AuthenticatedVendorBranchesRoute
  '/r/$slug/$branchCode': typeof RSlugBranchCodeRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/branch/': typeof AuthenticatedBranchIndexRoute
  '/_authenticated/vendor/': typeof AuthenticatedVendorIndexRoute
  '/_authenticated/admin/restaurants/$id': typeof AuthenticatedAdminRestaurantsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/menu'
    | '/reset-password'
    | '/sitemap.xml'
    | '/account'
    | '/admin'
    | '/branch'
    | '/favorites'
    | '/orders'
    | '/vendor'
    | '/food/$id'
    | '/r/$slug'
    | '/r/'
    | '/admin/analytics'
    | '/admin/branches'
    | '/admin/categories'
    | '/admin/coupons'
    | '/admin/foods'
    | '/admin/orders'
    | '/admin/reports'
    | '/admin/restaurants'
    | '/admin/users'
    | '/branch/inventory'
    | '/branch/orders'
    | '/branch/reports'
    | '/orders/$id'
    | '/vendor/analytics'
    | '/vendor/branches'
    | '/r/$slug/$branchCode'
    | '/admin/'
    | '/branch/'
    | '/vendor/'
    | '/admin/restaurants/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/menu'
    | '/reset-password'
    | '/sitemap.xml'
    | '/account'
    | '/favorites'
    | '/orders'
    | '/food/$id'
    | '/r/$slug'
    | '/r'
    | '/admin/analytics'
    | '/admin/branches'
    | '/admin/categories'
    | '/admin/coupons'
    | '/admin/foods'
    | '/admin/orders'
    | '/admin/reports'
    | '/admin/restaurants'
    | '/admin/users'
    | '/branch/inventory'
    | '/branch/orders'
    | '/branch/reports'
    | '/orders/$id'
    | '/vendor/analytics'
    | '/vendor/branches'
    | '/r/$slug/$branchCode'
    | '/admin'
    | '/branch'
    | '/vendor'
    | '/admin/restaurants/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/menu'
    | '/reset-password'
    | '/sitemap.xml'
    | '/_authenticated/account'
    | '/_authenticated/admin'
    | '/_authenticated/branch'
    | '/_authenticated/favorites'
    | '/_authenticated/orders'
    | '/_authenticated/vendor'
    | '/food/$id'
    | '/r/$slug'
    | '/r/'
    | '/_authenticated/admin/analytics'
    | '/_authenticated/admin/branches'
    | '/_authenticated/admin/categories'
    | '/_authenticated/admin/coupons'
    | '/_authenticated/admin/foods'
    | '/_authenticated/admin/orders'
    | '/_authenticated/admin/reports'
    | '/_authenticated/admin/restaurants'
    | '/_authenticated/admin/users'
    | '/_authenticated/branch/inventory'
    | '/_authenticated/branch/orders'
    | '/_authenticated/branch/reports'
    | '/_authenticated/orders/$id'
    | '/_authenticated/vendor/analytics'
    | '/_authenticated/vendor/branches'
    | '/r/$slug/$branchCode'
    | '/_authenticated/admin/'
    | '/_authenticated/branch/'
    | '/_authenticated/vendor/'
    | '/_authenticated/admin/restaurants/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  ContactRoute: typeof ContactRoute
  MenuRoute: typeof MenuRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  FoodIdRoute: typeof FoodIdRoute
  RSlugRoute: typeof RSlugRouteWithChildren
  RIndexRoute: typeof RIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu': {
      id: '/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof MenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/branch': {
      id: '/_authenticated/branch'
      path: '/branch'
      fullPath: '/branch'
      preLoaderRoute: typeof AuthenticatedBranchRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/favorites': {
      id: '/_authenticated/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof AuthenticatedFavoritesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/orders': {
      id: '/_authenticated/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof AuthenticatedOrdersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/vendor': {
      id: '/_authenticated/vendor'
      path: '/vendor'
      fullPath: '/vendor'
      preLoaderRoute: typeof AuthenticatedVendorRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/food/$id': {
      id: '/food/$id'
      path: '/food/$id'
      fullPath: '/food/$id'
      preLoaderRoute: typeof FoodIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/': {
      id: '/r/'
      path: '/r'
      fullPath: '/r/'
      preLoaderRoute: typeof RIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$slug': {
      id: '/r/$slug'
      path: '/r/$slug'
      fullPath: '/r/$slug'
      preLoaderRoute: typeof RSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/analytics': {
      id: '/_authenticated/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AuthenticatedAdminAnalyticsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/branches': {
      id: '/_authenticated/admin/branches'
      path: '/branches'
      fullPath: '/admin/branches'
      preLoaderRoute: typeof AuthenticatedAdminBranchesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/categories': {
      id: '/_authenticated/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AuthenticatedAdminCategoriesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/coupons': {
      id: '/_authenticated/admin/coupons'
      path: '/coupons'
      fullPath: '/admin/coupons'
      preLoaderRoute: typeof AuthenticatedAdminCouponsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/foods': {
      id: '/_authenticated/admin/foods'
      path: '/foods'
      fullPath: '/admin/foods'
      preLoaderRoute: typeof AuthenticatedAdminFoodsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/orders': {
      id: '/_authenticated/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AuthenticatedAdminOrdersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/reports': {
      id: '/_authenticated/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AuthenticatedAdminReportsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/restaurants': {
      id: '/_authenticated/admin/restaurants'
      path: '/restaurants'
      fullPath: '/admin/restaurants'
      preLoaderRoute: typeof AuthenticatedAdminRestaurantsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/branch/': {
      id: '/_authenticated/branch/'
      path: '/'
      fullPath: '/branch/'
      preLoaderRoute: typeof AuthenticatedBranchIndexRouteImport
      parentRoute: typeof AuthenticatedBranchRoute
    }
    '/_authenticated/branch/inventory': {
      id: '/_authenticated/branch/inventory'
      path: '/inventory'
      fullPath: '/branch/inventory'
      preLoaderRoute: typeof AuthenticatedBranchInventoryRouteImport
      parentRoute: typeof AuthenticatedBranchRoute
    }
    '/_authenticated/branch/orders': {
      id: '/_authenticated/branch/orders'
      path: '/orders'
      fullPath: '/branch/orders'
      preLoaderRoute: typeof AuthenticatedBranchOrdersRouteImport
      parentRoute: typeof AuthenticatedBranchRoute
    }
    '/_authenticated/branch/reports': {
      id: '/_authenticated/branch/reports'
      path: '/reports'
      fullPath: '/branch/reports'
      preLoaderRoute: typeof AuthenticatedBranchReportsRouteImport
      parentRoute: typeof AuthenticatedBranchRoute
    }
    '/_authenticated/orders/$id': {
      id: '/_authenticated/orders/$id'
      path: '/$id'
      fullPath: '/orders/$id'
      preLoaderRoute: typeof AuthenticatedOrdersIdRouteImport
      parentRoute: typeof AuthenticatedOrdersRoute
    }
    '/_authenticated/vendor/': {
      id: '/_authenticated/vendor/'
      path: '/'
      fullPath: '/vendor/'
      preLoaderRoute: typeof AuthenticatedVendorIndexRouteImport
      parentRoute: typeof AuthenticatedVendorRoute
    }
    '/_authenticated/vendor/analytics': {
      id: '/_authenticated/vendor/analytics'
      path: '/analytics'
      fullPath: '/vendor/analytics'
      preLoaderRoute: typeof AuthenticatedVendorAnalyticsRouteImport
      parentRoute: typeof AuthenticatedVendorRoute
    }
    '/_authenticated/vendor/branches': {
      id: '/_authenticated/vendor/branches'
      path: '/branches'
      fullPath: '/vendor/branches'
      preLoaderRoute: typeof AuthenticatedVendorBranchesRouteImport
      parentRoute: typeof AuthenticatedVendorRoute
    }
    '/r/$slug/$branchCode': {
      id: '/r/$slug/$branchCode'
      path: '/$branchCode'
      fullPath: '/r/$slug/$branchCode'
      preLoaderRoute: typeof RSlugBranchCodeRouteImport
      parentRoute: typeof RSlugRoute
    }
    '/_authenticated/admin/restaurants/$id': {
      id: '/_authenticated/admin/restaurants/$id'
      path: '/$id'
      fullPath: '/admin/restaurants/$id'
      preLoaderRoute: typeof AuthenticatedAdminRestaurantsIdRouteImport
      parentRoute: typeof AuthenticatedAdminRestaurantsRoute
    }
  }
}

interface AuthenticatedAdminRestaurantsRouteChildren {
  AuthenticatedAdminRestaurantsIdRoute: typeof AuthenticatedAdminRestaurantsIdRoute
}

const AuthenticatedAdminRestaurantsRouteChildren: AuthenticatedAdminRestaurantsRouteChildren =
  {
    AuthenticatedAdminRestaurantsIdRoute: AuthenticatedAdminRestaurantsIdRoute,
  }

const AuthenticatedAdminRestaurantsRouteWithChildren =
  AuthenticatedAdminRestaurantsRoute._addFileChildren(
    AuthenticatedAdminRestaurantsRouteChildren,
  )

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAnalyticsRoute: typeof AuthenticatedAdminAnalyticsRoute
  AuthenticatedAdminBranchesRoute: typeof AuthenticatedAdminBranchesRoute
  AuthenticatedAdminCategoriesRoute: typeof AuthenticatedAdminCategoriesRoute
  AuthenticatedAdminCouponsRoute: typeof AuthenticatedAdminCouponsRoute
  AuthenticatedAdminFoodsRoute: typeof AuthenticatedAdminFoodsRoute
  AuthenticatedAdminOrdersRoute: typeof AuthenticatedAdminOrdersRoute
  AuthenticatedAdminReportsRoute: typeof AuthenticatedAdminReportsRoute
  AuthenticatedAdminRestaurantsRoute: typeof AuthenticatedAdminRestaurantsRouteWithChildren
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAnalyticsRoute: AuthenticatedAdminAnalyticsRoute,
  AuthenticatedAdminBranchesRoute: AuthenticatedAdminBranchesRoute,
  AuthenticatedAdminCategoriesRoute: AuthenticatedAdminCategoriesRoute,
  AuthenticatedAdminCouponsRoute: AuthenticatedAdminCouponsRoute,
  AuthenticatedAdminFoodsRoute: AuthenticatedAdminFoodsRoute,
  AuthenticatedAdminOrdersRoute: AuthenticatedAdminOrdersRoute,
  AuthenticatedAdminReportsRoute: AuthenticatedAdminReportsRoute,
  AuthenticatedAdminRestaurantsRoute:
    AuthenticatedAdminRestaurantsRouteWithChildren,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedBranchRouteChildren {
  AuthenticatedBranchInventoryRoute: typeof AuthenticatedBranchInventoryRoute
  AuthenticatedBranchOrdersRoute: typeof AuthenticatedBranchOrdersRoute
  AuthenticatedBranchReportsRoute: typeof AuthenticatedBranchReportsRoute
  AuthenticatedBranchIndexRoute: typeof AuthenticatedBranchIndexRoute
}

const AuthenticatedBranchRouteChildren: AuthenticatedBranchRouteChildren = {
  AuthenticatedBranchInventoryRoute: AuthenticatedBranchInventoryRoute,
  AuthenticatedBranchOrdersRoute: AuthenticatedBranchOrdersRoute,
  AuthenticatedBranchReportsRoute: AuthenticatedBranchReportsRoute,
  AuthenticatedBranchIndexRoute: AuthenticatedBranchIndexRoute,
}

const AuthenticatedBranchRouteWithChildren =
  AuthenticatedBranchRoute._addFileChildren(AuthenticatedBranchRouteChildren)

interface AuthenticatedOrdersRouteChildren {
  AuthenticatedOrdersIdRoute: typeof AuthenticatedOrdersIdRoute
}

const AuthenticatedOrdersRouteChildren: AuthenticatedOrdersRouteChildren = {
  AuthenticatedOrdersIdRoute: AuthenticatedOrdersIdRoute,
}

const AuthenticatedOrdersRouteWithChildren =
  AuthenticatedOrdersRoute._addFileChildren(AuthenticatedOrdersRouteChildren)

interface AuthenticatedVendorRouteChildren {
  AuthenticatedVendorAnalyticsRoute: typeof AuthenticatedVendorAnalyticsRoute
  AuthenticatedVendorBranchesRoute: typeof AuthenticatedVendorBranchesRoute
  AuthenticatedVendorIndexRoute: typeof AuthenticatedVendorIndexRoute
}

const AuthenticatedVendorRouteChildren: AuthenticatedVendorRouteChildren = {
  AuthenticatedVendorAnalyticsRoute: AuthenticatedVendorAnalyticsRoute,
  AuthenticatedVendorBranchesRoute: AuthenticatedVendorBranchesRoute,
  AuthenticatedVendorIndexRoute: AuthenticatedVendorIndexRoute,
}

const AuthenticatedVendorRouteWithChildren =
  AuthenticatedVendorRoute._addFileChildren(AuthenticatedVendorRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRoute
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedBranchRoute: typeof AuthenticatedBranchRouteWithChildren
  AuthenticatedFavoritesRoute: typeof AuthenticatedFavoritesRoute
  AuthenticatedOrdersRoute: typeof AuthenticatedOrdersRouteWithChildren
  AuthenticatedVendorRoute: typeof AuthenticatedVendorRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAccountRoute: AuthenticatedAccountRoute,
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedBranchRoute: AuthenticatedBranchRouteWithChildren,
  AuthenticatedFavoritesRoute: AuthenticatedFavoritesRoute,
  AuthenticatedOrdersRoute: AuthenticatedOrdersRouteWithChildren,
  AuthenticatedVendorRoute: AuthenticatedVendorRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface RSlugRouteChildren {
  RSlugBranchCodeRoute: typeof RSlugBranchCodeRoute
}

const RSlugRouteChildren: RSlugRouteChildren = {
  RSlugBranchCodeRoute: RSlugBranchCodeRoute,
}

const RSlugRouteWithChildren = RSlugRoute._addFileChildren(RSlugRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  ContactRoute: ContactRoute,
  MenuRoute: MenuRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  FoodIdRoute: FoodIdRoute,
  RSlugRoute: RSlugRouteWithChildren,
  RIndexRoute: RIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
